# ===============================
# Mysql  Database
# ===============================

spring.application.name=prms
spring.datasource.url=jdbc:mysql://localhost:3306/prms?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Mysql@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# ===============================
# Oracle Database
# ===============================

#spring.application.name=prms
#spring.datasource.url=jdbc:oracle:thin:@10.243.6.48:1539/ORCLPDB
#spring.datasource.username=prms
#spring.datasource.password=prms
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

